version: 2

before:
  hooks:
    - go mod tidy

builds:
  - env:
      - CGO_ENABLED=0
    goos:
      - linux
      - windows
      - darwin

archives:
  - formats: [tar.gz]
    # this name template makes the OS and Arch compatible with the results of `uname`.
    name_template: >-
      {{ .ProjectName }}_
      {{- .Os }}_
      {{- .Version }}_
      {{- if eq .Arch "amd64" }}x86_64
      {{- else if eq .Arch "386" }}i386
      {{- else }}{{ .Arch }}{{ end }}
      {{- if .Arm }}v{{ .Arm }}{{ end }}
    # use zip for windows archives
    format_overrides:
      - goos: windows
        formats: [zip]

changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"

# MacOS
universal_binaries:
  - replace: true

nfpms:
  - id: linux-package
    homepage: "https://github.com/xitonix/grls"
    maintainer: "{{ .Env.MAINTAINER }}"
    description: "A CLI tool for Kafka"
    license: "Apache License 2.0"
    formats:
      - apk
      - deb
      - rpm

chocolateys:
  -
    project_url: "https://github.com/xitonix/grls"
    owners: "Alex Golshani"
    authors: "Alex Golshani"
    require_license_acceptance: false
    description: "{{ .Env.DESCRIPTION }}"
    api_key: "{{ .Env.CHOCOLATEY_API_KEY }}"
    skip_publish: false