name: release
env:
  GO_VERSION: 1.24.2
  MAINTAINER: Alex Golshani
  URL: https://github.com/xitonix/trubka
  DESCRIPTION: A CLI tool for Kafka
  LICENSE: Apache License 2.0
  APPLICATION: grls
on:
  pull_request:
  push:
    # run only against tags
    tags:
      - "*"

permissions:
  contents: write

jobs:
#  GoRelease:
#    runs-on: ubuntu-latest
#    steps:
#      - name: Checkout
#        uses: actions/checkout@v4
#        with:
#          fetch-depth: 0
#      - name: Set up Go
#        uses: actions/setup-go@v5
#        with:
#          go-version: ${{ env.GO_VERSION }}
#      - name: Run GoReleaser
#        uses: goreleaser/goreleaser-action@v6
#        with:
#          # either 'goreleaser' (default) or 'goreleaser-pro'
#          distribution: goreleaser
#          # 'latest', 'nightly', or a semver
#          version: "~> v2"
#          args: release --clean
#        env:
#          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  windows:
    name: Windows-MSI
    runs-on: windows-latest
    steps:
      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: ${{ env.GO_VERSION }}
      - name: Check out code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Download dependencies
        run: go mod download -x
        env:
          GO111MODULE: on
      - name: Package release
        run: .\release.ps1
        working-directory: .\release\windows
        id: package
        env:
          GO111MODULE: on
      - name: Upload windows artifacts
        uses: softprops/action-gh-release@v2
        if: github.ref_type == 'tag'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          files: |
            ./release/windows/${{ steps.package.outputs.msi }}