name: release
env:
  GO_VERSION: 1.24.2
  MAINTAINER: Alex Golshani
  DESCRIPTION: A CLI tool for Kafka
  LICENSE: Apache License 2.0
  CHOCOLATEY_API_KEY: ${{ secrets.CHOCOLATEY_API_KEY }}
  APPLICATION: grls
on:
  pull_request:
  push:
    # run only against tags
    tags:
      - "v*.*.*"

permissions:
  contents: write

jobs:
  go-releaser:
    runs-on: windows-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: ${{ env.GO_VERSION }}
          cache: false
      - name: Verify Chocolatey installation
        run: choco --version
      - name: Run GoReleaser
        uses: goreleaser/goreleaser-action@v6
        with:
          distribution: goreleaser
          version: "~> v2"
          args: release --clean
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Build Windows MSI Package
        run: .\release.ps1
        working-directory: .\release\windows
        id: package
        env:
          GO111MODULE: on
      - name: Upload Windows MSI
        uses: softprops/action-gh-release@v2
        if: github.ref_type == 'tag'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          files: |
            ./release/windows/${{ steps.package.outputs.msi }}
